name: dmp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase Packages ---
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.8
  google_sign_in: ^6.2.2

  # --- State Management ---
  provider: ^6.1.2

  # --- UI & Utility Packages ---
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  file_picker: ^8.1.4
  url_launcher: ^6.3.1
  pdf: ^3.11.1
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  lucide_icons: ^0.257.0
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/backg.jpg
    - assets/images/view.jpg
    - assets/images/office.jpg
    - assets/images/dmplogofinal.png
    - assets/images/lawn.jpg
    - assets/images/memorialg.jpg
    - assets/images/gardenfam.jpg
    - assets/images/mausoleum.jpg
    - assets/images/dmp.png
    - assets/images/lasp.jpg
    - assets/images/lap.jpg
    - assets/images/laprime.jpg
    - assets/images/lar.jpg
    - assets/images/mgsp.jpg
    - assets/images/mgr.jpg
    - assets/images/gfp.jpg
    - assets/images/gfsp.jpg